# Generated by Django 4.2.11 on 2026-06-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('filler_word_count', models.IntegerField(default=0)),
                ('avg_pace_wpm', models.FloatField(default=0)),
                ('posture_score', models.FloatField(default=0)),
                ('feedback_text', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
            ],
        ),
    ]
