# Generated by Django 4.2.11 on 2026-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='eye_contact_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='gestures_per_minute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='openness_score',
            field=models.FloatField(default=0),
        ),
    ]
