# Generated by Django 4.2.11 on 2026-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_practicesession_eye_contact_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='blink_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='mouth_openness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='smile_score',
            field=models.IntegerField(default=0),
        ),
    ]
