# Generated by Django 4.2.11 on 2026-06-27 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_practicesession_blink_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='student_id',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
